name: UPDATE

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm packages & update
        run: |
          npm ci
          npm update

      - name: Test
        run: npm run test

      - name: Test all
        run: npm run test-all
